### PR TITLE
Added visibility toggle for symlinks

### LINKED ISSUE #1352: How to hide file links in the directory tree?
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question

After searching through the documentation for nerdtree, I couldn't find a way to hide file links in the directory tree. What can I do? 

Xnip2023-03-14_19-50-43

### PR DESCRIPTION
**Pull request by rzvxa**
… of symlinks.

### Description of Changes
Closes #1352

Added a new setting `g:NERDTreeShowSymlink`, For filtering symlinks, This setting can be dynamically toggled, per tree, with the <NERDTree-S> mapping.

---
#### Author's Instructions
- [ ] Derive a new `MAJOR.MINOR.PATCH` version number. Increment the:
    - `MAJOR` version when you make incompatible API changes
    - `MINOR` version when you add functionality in a backwards-compatible manner
    - `PATCH` version when you make backwards-compatible bug fixes
- [ ] Update [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), following the established pattern.
#### Collaborator's Instructions
- [ ] Review [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), suggesting a different version number if necessary.
- [ ] After merging, tag the commit using these (Mac-compatible) bash commands:
    ```bash
    git checkout master
    git pull
    sed -n "$(grep -n -m2 '####' CHANGELOG.md | cut -f1 -d: | sed 'N;s/\n/,/')p" CHANGELOG.md | sed '$d'
    git tag -a $(read -p "Tag Name: " tag;echo $tag) -m"$(git show --quiet --pretty=%s)";git push origin --tags
    ```

### CODE REVIEW

**Comment by rzvxa** [comment]
https://github.com/preservim/nerdtree/assets/3788964/b39e9868-2dd2-409e-b859-ca9a5d2899a4



https://github.com/preservim/nerdtree/assets/3788964/8e075b28-e4e1-4c20-8bbf-5fbb63dbc040

**Review by alerque — COMMENTED** [review]
I'm not convinced this addresses the feature request. I think the issue opener just wanted to hide the *target* of the links, not the fact that symlinks even existed. To be honest I'd hesitate to include this. I've seen tons of file manager interfaces that hide hidden files, but can't think of *any* that completely hide the existence of symlinks. At the very least I'd expect first to have the functionality to hide the targets (which look a little noisy) and only then to consider what the use case is for completely ignoring them.

**Comment by rzvxa** [comment]
> I'm not convinced this addresses the feature request. I think the issue opener just wanted to hide the _target_ of the links, not the fact that symlinks even existed. To be honest I'd hesitate to include this. I've seen tons of file manager interfaces that hide hidden files, but can't think of _any_ that completely hide the existence of symlinks. At the very least I'd expect first to have the functionality to hide the targets (which look a little noisy) and only then to consider what the use case is for completely ignoring them.

I'm up for closing this PR, at first it seemed natural to add the ability to hide symlinks, But now that I'm thinking again about it, I think you are right maybe only hiding the linked path is enough

**Comment by alerque** [comment]
I'll close this for now. We can reconsider if anybody has a use case for it that they want to pitch. Personally I don't have one and can't imagine one, but that doesn't mean one doesn't exist. If we do include something like this it would be nice to know it actually met a need and didn't just add clutter to the docs.

In the mean time an option to hide symlink targets does seem to make sense to me.

**Pull request closed without merging**
