### PR TITLE
Add memrise course to starting guide.

### PR DESCRIPTION
**Pull request by EsmaeilSaleh**
### Description of Changes
Closes #    

---
#### Author's Instructions
- [ ] Derive a new `MAJOR.MINOR.PATCH` version number. Increment the:
    - `MAJOR` version when you make incompatible API changes
    - `MINOR` version when you add functionality in a backwards-compatible manner
    - `PATCH` version when you make backwards-compatible bug fixes
- [ ] Update [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), following the established pattern.
#### Collaborator's Instructions
- [ ] Review [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), suggesting a different version number if necessary.
- [ ] After merging, tag the commit using these (Mac-compatible) bash commands:
    ```bash
    git checkout master
    git pull
    sed -n "$(grep -n -m2 '####' CHANGELOG.md | cut -f1 -d: | sed 'N;s/\n/,/')p" CHANGELOG.md | sed '$d'
    git tag -a $(read -p "Tag Name: " tag;echo $tag) -m"$(git show --quiet --pretty=%s)";git push origin --tags
    ```

### CODE REVIEW

**Comment by igbanam** [comment]
So… thinking user-experience, it's most beneficial to Vim users to get all the help they need from within Vim. This is why there is a high bar on Vim documentation. Having to context-switch into the browser to learn mappings whose docs are already available locally in the editor seems like quite the travel to me. I don't see why users would need this.

**Comment by EsmaeilSaleh** [comment]
You are absolutely right. But Its not the point of this course. You will learn/memorize the Keybindings once and that's it. You won't need to travel even to docs! And that's fast. Try it.

**Comment by igbanam** [comment]
Why not encourage people to learn the key bindings from the docs?

**Comment by EsmaeilSaleh** [comment]
Ok Wow! This is getting weird! Its not about learning, its more about memorizing! You should learn them in docs. This Memrise thing is a tool that helps you to memorize things!

**Pull request closed without merging**
