### PR TITLE
fix: change default binding of filelines to `FL`.

### LINKED ISSUE #1399: BUG: NERDTree Hijacked Movement Keys
A recent change in #1384 conflicts with a common navigation style for hopping up and down the buffer.

# Reproduction Steps

1. Open a large project in VIM
2. Show NERDTree
3. Attempt to navigate to the bottom of the buffer with `L`

## Expected Behavior

Caret jumps to the bottom of NERDTree's buffer

## Actual Behavior

NERDTree displays Number of Lines next to files

-----------

This breaks consistency among buffers, especially for something as fundamental as navigation.

### PR DESCRIPTION
**Pull request by rzvxa**
### Description of Changes
Closes #1399 

---
### New Version Info

Changes the Toggle File Lines binding from `L` to `FL` to prevent all clashes.
`F` will prevent backward find in the line but both `F` and `f` are already taken as shortcuts in the NERDTree buffer so won't break anything that is already working there.

### CODE REVIEW

**Comment by rzvxa** [comment]
@Swivelgames Please give it an approving review if you do agree with this new shortcut so we can speed up the merging process.

**Review by Swivelgames — APPROVED** [review]
Looks good! Thanks for the speedy turnaround 🚀

**Review by alerque — APPROVED** [review]

**Comment by rzvxa** [comment]
@isaiah I just mentioned you here to let you know that the issue discussed in #1384 has been fixed and now you can use the default bindings instead of using the configuration I gave you.

I thought the first report by you was just a fluke but with a second open issue for it on hand I soon realized It may have affected more people than I initially thought so I Just wanted to apologize for this.

Have a great day guys and thank you both for reporting this!

**Comment by Swivelgames** [comment]
Works beautifully. Thanks again!

**Pull request merged**
