### PR TITLE
Added reveal functionality for Windows platform in fs_menu

### PR DESCRIPTION
**Pull request by rzvxa**
### Description of Changes
Adds similar functionality to Linux and Mac platforms for revealing the selected node in the file browser(in the case of Windows It's `Windows Explorer`)

---
#### Author's Instructions
- [ ] Derive a new `MAJOR.MINOR.PATCH` version number. Increment the:
    - `MAJOR` version when you make incompatible API changes
    - `MINOR` version when you add functionality in a backwards-compatible manner
    - `PATCH` version when you make backwards-compatible bug fixes
- [ ] Update [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), following the established pattern.
#### Collaborator's Instructions
- [ ] Review [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), suggesting a different version number if necessary.
- [ ] After merging, tag the commit using these (Mac-compatible) bash commands:
    ```bash
    git checkout master
    git pull
    sed -n "$(grep -n -m2 '####' CHANGELOG.md | cut -f1 -d: | sed 'N;s/\n/,/')p" CHANGELOG.md | sed '$d'
    git tag -a $(read -p "Tag Name: " tag;echo $tag) -m"$(git show --quiet --pretty=%s)";git push origin --tags
    ```

### CODE REVIEW

**Comment by rzvxa** [comment]
@alerque This PR adds the missing Reveal in Explorer to the Windows platform.

**Review by alerque — DISMISSED** [review]
This looks good to me, but I'm also not on either macOS or Windows to test it. It would be nice if we could get at least one confirmation from another party that this is working for them.

**Comment by rzvxa** [comment]
> This looks good to me, but I'm also not on either macOS or Windows to test it. It would be nice if we could get at least one confirmation from another party that this is working for them.

Mac functionality was already implemented before this PR, I just changed its text to match other shortcuts.

**Comment by alerque** [comment]
Great. Do we have 1 other Windows user that can give this a spin?

(If it goes too long with no review we'll probably just merge and let people complain if it broke, but I always try to get feedback/reviews for things I can't test even if they look sane.)

**Comment by rzvxa** [comment]
@alerque Hi, Do you think it's fine to move forward with this PR? I personally would love to use it in my day-to-day life since I'm using this functionality on my Linux machine, after all, it adds a new functionality and won't break any existing one.

**Review by alerque — APPROVED** [review]

**Pull request merged**
