### PR TITLE
Fixes #1272

### LINKED ISSUE #1272: Nerdtree window switches/swaps with main window,  when opened with directory as argument
#### Environment
- Operating System: x86_64 GNU/Linux, 5.4.45
- Vim/Neovim version `:version`: v0.5.1
- NERDTree version, found on first line of quickhelp `?`: 6.10.16
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
if has("nvim")
  let g:plug_home = stdpath('data') . '/plugged'
endif

call plug#begin()
Plug 'preservim/nerdtree'
call plug#end()

autocmd!  
set number relativenumber
syntax enable
set encoding=utf-8
set background=dark
set hidden 
set confirm
set nobackup
set nowritebackup
set noswapfile
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set termguicolors

let mapleader = "\<Space>"
nnoremap <silent> Q :q<CR>
nnoremap <silent><C-n> :NERDTreeToggle<CR>

let g:NERDTreeChDirMode=2
let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '^__pycache__$', '^node_modules$']
let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
let g:NERDTreeShowBookmarks=1
let g:nerdtree_tabs_focus_on_files=1
let g:NERDTreeGitStatusWithFlags = 1

" How can I close vim if the only window left open is a NERDTree?
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" If another buffer tries to replace NERDTree, put it in the other window, and bring back NERDTree.
autocmd BufEnter * if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1 |
    \ let buf=bufnr() | buffer# | execute "normal! \<C-W>w" | execute 'buffer'.buf | endif

" Open the existing NERDTree on each new tab.
"autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

```

#### Steps to Reproduce the Issue
1. Invoke nvim with directory as argument
2. navigate and try to open any file.
3. invoke nerdtree (`:NERDTreeToggle`)
4. try to switch between nerdtree window and file window. you can use any  map`<c-w><c-h>`,`<c-w>w` or `:wincmd h`.

https://user-images.githubusercontent.com/47944176/135973428-685b5bdf-e284-4abd-8e47-4f637d43655a.mp4

### PR DESCRIPTION
**Pull request by BubuDavid**
### Description of Changes
Closes #1272    

---
#### Author's Instructions
- [ ] Derive a new `MAJOR.MINOR.PATCH` version number. Increment the:
    - `MAJOR` version when you make incompatible API changes
    - `MINOR` version when you add functionality in a backwards-compatible manner
    - `PATCH` version when you make backwards-compatible bug fixes
- [ ] Update [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), following the established pattern.
#### Collaborator's Instructions
- [ ] Review [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), suggesting a different version number if necessary.
- [ ] After merging, tag the commit using these (Mac-compatible) bash commands:
    ```bash
    git checkout master
    git pull
    sed -n "$(grep -n -m2 '####' CHANGELOG.md | cut -f1 -d: | sed 'N;s/\n/,/')p" CHANGELOG.md | sed '$d'
    git tag -a $(read -p "Tag Name: " tag;echo $tag) -m"$(git show --quiet --pretty=%s)";git push origin --tags
    ```

### CODE REVIEW

**Review by rzvxa — APPROVED** [review]
@BubuDavid Thanks for the change
@alerque Would you mind reviewing this PR?

**Review by alerque — APPROVED** [review]

**Comment by rzvxa** [comment]
Hello @BubuDavid,

I would like to go ahead and merge this PR. Can you rebase your work to the current version of the master?
If you don't have time to do so Or have lost interest in doing so I can do it for you, If that is the case just let me know.
I'm sorry it took a while before merging it.

**Comment by alerque** [comment]
@rzvxa This doesn't need rebasing, you can merge with the "rebase and merge" option to get linear history while keeping the commits from the PR intact or "squash and merge" if the PR has messy commit history but is overall a small single-purpose set of changes. You only really need to rebase inside a PR if there are going to be merge conflicts or some testing/review is proving hard to do on an old branch point.

**Comment by rzvxa** [comment]
Since this one is already rebased and also original author is kept intact I'm going to move forward with merging it, But I want to know if the right way is doing the merge commit instead. I don't like it when commits get changed, And I wasn't aware of the fact that GitHub doesn't respect the original commit author information, Since most of my work is in a closed source environment it wasn't an issue for me until now. I would love it if you could tell me how to update a branch in GitHub PR without changing the commits and ideally without any additional merge commit on top, Until I find out more about it I'm going to use merge commit since it won't rewrite the commits in the fork even tho I'm not a big fan of merge commits for small changes like this. (For more complex changes it makes sense to me since you get merge conflicts, But a one-file change where it's only behind by a commit is pretty obvious that won't have any conflicts)
Pardon me if I got it wrong. I'm used to thinking about commits as diffs, So in my mind, it won't affect the overall outcome if you apply a diff before or after another one when they are changing different files.

**Pull request merged**
