### PR TITLE
Warn invalid files

### PR DESCRIPTION
**Pull request by rzvxa**
### Description of Changes
Closes #1274

---
### New Version Info
Fixed issues with the original PR

#### Author's Instructions
- [ ] Derive a new `MAJOR.MINOR.PATCH` version number. Increment the:
    - `MAJOR` version when you make incompatible API changes
    - `MINOR` version when you add functionality in a backwards-compatible manner
    - `PATCH` version when you make backwards-compatible bug fixes
- [ ] Update [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), following the established pattern.
#### Collaborator's Instructions
- [ ] Review [CHANGELOG.md](https://github.com/scrooloose/nerdtree/blob/master/CHANGELOG.md), suggesting a different version number if necessary.
- [ ] After merging, tag the commit using these (Mac-compatible) bash commands:
    ```bash
    git checkout master
    git pull
    sed -n "$(grep -n -m2 '####' CHANGELOG.md | cut -f1 -d: | sed 'N;s/\n/,/')p" CHANGELOG.md | sed '$d'
    git tag -a $(read -p "Tag Name: " tag;echo $tag) -m"$(git show --quiet --pretty=%s)";git push origin --tags
    ```

### CODE REVIEW

**Review by alerque — CHANGES_REQUESTED** [review]
Thanks for helping out with existing PRs. I would like to make sure we keep credit for the original author though. Somehow you've rewritten the original commits instead of keeping them. Can you please rebase this on the other PR commits so the original author meta data is kept, and then your commit appended to the list? At most I would squash them and use Co-authored-by headers, but separate commits is fine too. They just need to be at least partial credit to the OP.

**Comment by rzvxa** [comment]
> Thanks for helping out with existing PRs. I would like to make sure we keep credit for the original author though. Somehow you've rewritten the original commits instead of keeping them. Can you please rebase this on the other PR commits so the original author meta data is kept, and then your commit appended to the list? At most I would squash them and use Co-authored-by headers, but separate commits is fine too. They just need to be at least partial credit to the OP.

I've tried rebasing but git complains about untracked references between branches which `NERDTreeRevealFileLinux` are implemented for mac and linux but there is no implementation for windows reveal in explorer

**Comment by rzvxa** [comment]
> Thanks for helping out with existing PRs. I would like to make sure we keep credit for the original author though. Somehow you've rewritten the original commits instead of keeping them. Can you please rebase this on the other PR commits so the original author meta data is kept, and then your commit appended to the list? At most I would squash them and use Co-authored-by headers, but separate commits is fine too. They just need to be at least partial credit to the OP.

Initially, I tried to rebase but Git complained about broken references as there were some removed commits here and there, So I just used cherry-picking to patch my fork, I can go back and get the original commit in, But it would be much easier to add credit on the merge commit.
If you don't want to do it this way, Tell me so I can go ahead and rebase it for real this time

**Comment by alerque** [comment]
> Initially, I tried to rebase but Git complained about broken references as there were some removed commits here and there, So I just used cherry-picking to patch my fork, I can go back and get the original commit in, But it would be much easier to add credit on the merge commit.

No, there are no removed commits between that PR and this one. The are only 4 commits apart in the tree, and it would be impossible for the other PR to even be valid if it wasn't based on this repository. I didn't have any trouble rebasing your commits here onto the original PR.

> If you don't want to do it this way, Tell me so I can go ahead and rebase it for real this time

I just did, and also merged one of the commits. You can give it a look here and if all looks okay to you I think we can merge.

**Review by alerque — APPROVED** [review]

**Comment by rzvxa** [comment]
@alerque Thanks for merging the initial PR, Looks good to me, Let's go ahead and merge this.

**Pull request merged**
